### ISSUE TITLE
Spring boot 2x upgrade

### ISSUE THREAD

**Issue by shangal** [spring-cloud-services-samples/greeting#13]
Upgrading the greeter project 
for boot2 and spring-cloud-services-dependencies(2.0.0.M1) and Finchley.M9 i am getting the following error(i am using the pom to build)

[APP/PROC/WEB/0] [OUT] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

**Comment by shangal** [comment]
Ah! Thanks for the help. I got it working - i had to do couple of things...

1) For the original error - i had to include the dependency for spring-boot-actuator-autoconfigure
This got the app running.

But i had to disable the security too to make the app work.

**Comment by Bwvolleyball** [comment]
@shangal make sure you upgrade all of the <dependencyManagment> versions in the pom.xml to SB 2.0 compatible versions, or if you are using gradle, do the same thing in the mavenBom items.

To reiterate, you would need to set the spring boot version to 2.0, the spring cloud services to Finchley (e.g. FINCHLY.M9), and you would need to use the pivotal spring cloud services version of 2.0.0.SNAPSHOT since there is not a 2.0 release quite yet.

**Comment by royclarkson** [comment]
The latest code in master is now upgraded to support Spring Boot 2.0.2.RELEASE, Spring Cloud Finchley.RC2, and Spring Cloud Services 2.0.0.RC2.
