### ISSUE TITLE
Make the example URL's dynamic

### ISSUE THREAD

**Issue by asaikali** [spring-cloud-services-samples/greeting#7]
The example has hardcoded hostnames which means it can only be run once against a PCF instance before it breaks. It would be best if the app and deploy scripts were changed to use dynamic URLS just ${random-word} to the manifest. Since the service are registering with Eureka this should not be a problem since they will register with their correct URL.

**Comment by fifthposition** [comment]
Fixed in master:

* https://github.com/spring-cloud-services-samples/greeting/blob/master/greeter/manifest.yml
* https://github.com/spring-cloud-services-samples/greeting/blob/master/greeter-messages/manifest.yml
* https://github.com/spring-cloud-services-samples/greeting/blob/master/feign-greeter/manifest.yml
